### ISSUE TITLE
commits are not showing in the main branch

### ISSUE THREAD

**Issue by oizhamal** [Ermek37/uno#17]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/91153678/169383726-96db1950-be0d-4832-a7d4-635f290b6089.png">

here is the full code, but in the main it's not there

**Comment by acxcil** [comment]
Did you merge them? If not, you can go to pull requests and do it there.

**Comment by acxcil** [comment]
It appears your code had some conflicts with the main code. I merged it)

**Comment by oizhamal** [comment]
> It appears your code had some conflicts with the main code. I merged it)

THAAAAANKS! GOT MY ERROR NOW!
